/**
 * @File Name          : aabb.cls
 * @Description        : 
 * @Author             : mohitsharma.SFDoc
 * @Group              : 
 * @Last Modified By   : ChangeMeIn@UserSettingsUnder.SFDoc
 * @Last Modified On   : 1/4/2020, 9:50:25 pm
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    29/3/2020   ChangeMeIn@UserSettingsUnder.SFDoc     Initial Version
**/

public class aabb
{
@FUTURE
public static void temtestp()
{
batcs3 b = new batcs3();
Database.executeBatch(b,1);
}
}